version: 2.1
branches_only: &branches_only
  filters:
    branches:
      only:
        - alpha
        - beta
        - master

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t nextjs-docker .

  publish:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag nextjs-docker 001100/nextjs-docker
            docker push 001100/nextjs-docker

workflows:
  build_and_deploy:
    jobs:
      - build:
          <<: *branches_only
      - publish:
          <<: *branches_only
          requires:
            - build
